
/******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: Ultrasonic.c
 *
 * Description: Source file for the Ultrasonic driver
 *
 * Author: Omar Medhat
 *
 *******************************************************************************/
#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include "common_macros.h" /* To use the macros like SET_BIT */
#include  <util/delay.h>
/*******************************************************************************
 *                      Variable  Declaration                                  *
*******************************************************************************/
static uint8 g_edges_num = 0 ;
static uint16 g_time_high = 0 ;
static uint8 g_distance = 0 ;
/*******************************************************************************
 *                      Functions Definitions                                  *
*******************************************************************************/
/* Description
	1- Initialize the ICU driver as required.
	2- Setup the ICU call back function.
	3- Setup the direction for the trigger pin as output pin through the GPIO driver.
*/
void Ultrasonic_init(void)
{
	//Initialize the ICU driver with prescaler F_CPU_8 and the first edge to detect is rising edge
	Icu_ConfigType Icu_Configration ={F_CPU_8,RISING};
	// Setup the direction for the trigger pin as output pin;
	GPIO_setupPinDirection(Ultresonic_trigger_PORT_ID, Ultresonic_trigger_PIN_ID,PIN_OUTPUT);
	Icu_init(&Icu_Configration);
	//Ultrasonic_edgeProcessing function as Call Back Function to ICU
	Icu_setCallBack(Ultrasonic_edgeProcessing);

}
/* Description
	- Send the Trigger pulse to the ultrasonic for 10 micro second to start measurements .
 */

static void Ultrasonic_Trigger(void)
{
	GPIO_writePin(Ultresonic_trigger_PORT_ID, Ultresonic_trigger_PIN_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(Ultresonic_trigger_PORT_ID, Ultresonic_trigger_PIN_ID, LOGIC_LOW);
}
/*Description
 * 1- Clear all Global variables before start measurements for the previous measurments
 * 2- Clear ICU timer current value to start a new measurments.
 * 3- Send the trigger of Ultresonic by calling Ultrasonic_Trigger Function
 * 3- Start the measurements by the ICU from this moment.
 * 4- Wait until the ICU measure the required edges
 * 5- Calculate the distance in (cm) from this function
 * 	  { (Sound velocity in cm (34000)  *  Time   ) / 2 } and return its value
 * 6- Total distance is divided by 2 because signal travels
 *    from HC-SR04 to object and returns to the module HC-SR-0
 *
*/


uint16 Ultrasonic_readDistance(void)
{
	//Clear all global variables
	g_distance =0 ;
	g_edges_num=0 ;
	g_time_high=0;

	//Clear ICU timer current value
	Icu_clearTimerValue();

	//Send the trigger of Ultresonic
	Ultrasonic_Trigger();

	//Wait until reaching for the required number of edges that want to be detected
	while (g_edges_num != num_of_detected_edge);

	//Calculate the distance and return its value
	g_distance = (g_time_high / 58)+1;
	return g_distance ;
}

/*Description
 * 1- This is the call back function called by the ICU driver.
 * 2- This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
*/
static void Ultrasonic_edgeProcessing(void)
{

	g_edges_num++;
	if (g_edges_num ==1)
	{

		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if (g_edges_num==2)
	{
		/* Store the High time value */
		g_time_high = Icu_getInputCaptureValue();
		/* Detect  RISING edge*/
		Icu_setEdgeDetectionType(RISING);
	}
}
