/******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: Ultrasonic.h
 *
 * Description: Header file for the Ultrasonic driver
 *
 * Author: Omar Medhat
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_
#include "std_types.h"
#include "gpio.h"
/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define Ultresonic_trigger_PORT_ID        PORTB_ID
#define Ultresonic_trigger_PIN_ID          PIN5_ID
#define  num_of_detected_edge				 2

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/* Description
	1- Initialize the ICU driver as required.
	2- Setup the ICU call back function.
	3- Setup the direction for the trigger pin as output pin through the GPIO driver.
*/
void Ultrasonic_init(void);

/* Description
	- Send the Trigger pulse to the ultrasonic for 10 micro second to start measurements .
 */
static void Ultrasonic_Trigger(void);

/*Description
 * 1- Clear all Global variables before start measurements for the previous measurments
 * 2- Clear ICU timer current value to start a new measurments.
 * 3- Send the trigger of Ultresonic by calling Ultrasonic_Trigger Function
 * 3- Start the measurements by the ICU from this moment.
 * 4- Wait until the ICU measure the required edges
 * 5- Calculate the distance in (cm) from this function
 * 	  { (Sound velocity in cm (34000)  *  Time   ) / 2 } and return its value
 * 6- Total distance is divided by 2 because signal travels
 *    from HC-SR04 to object and returns to the module HC-SR-0
 *
*/
uint16 Ultrasonic_readDistance(void);

/*Description
 * 1- This is the call back function called by the ICU driver.
 * 2- This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
*/
static void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_H_ */
